export const Words = [
  { en: "Accept", tr: "Kabul etmek" },
  { en: "Accuse", tr: "Suçlamak" },
  { en: "Achieve", tr: "Başarmak" },
  { en: "Acknowledge", tr: "Kabul etmek" },
  { en: "Acquire", tr: "Elde etmek" },
  { en: "Adapt", tr: "Adapte etmek" },
  { en: "Add", tr: "Eklemek" },
  { en: "Adjust", tr: "Ayarlamak" },
  { en: "Admire", tr: "Hayranlık duymak" },
  { en: "Admit", tr: "Kabul, itiraf etmek" },
  { en: "Adopt", tr: "Evlat edinmek" },
  { en: "Adore", tr: "Beğenmek, bayılmak" },
  { en: "Advise", tr: "Öğüt vermek" },
  { en: "Afford", tr: "Parası yetmek" },
  { en: "Agree", tr: "Aynı fikirde olmak" },
  { en: "Aim", tr: "Hedeflemek" },
  { en: "Allow", tr: "İzin vermek" },
  { en: "Announce", tr: "Anons etmek" },
  { en: "Anticipate", tr: "Beklemek, ummak" },
  { en: "Apologize", tr: "Özür dilemek" },
  { en: "Appear", tr: "Belli olmak, görünmek" },
  { en: "Apply", tr: "Uygulamak, başvurmak" },
  { en: "Appreciate", tr: "Minnet duymak" },
  { en: "Approach", tr: "Yaklaşmak, yaklaşım" },
  { en: "Approve", tr: "Onaylamak" },
  { en: "Argue", tr: "Tartışmak" },
  { en: "Arise", tr: "Meydana çıkmak" },
  { en: "Arrange", tr: "Ayarlamak, düzenlemek" },
  { en: "Arrive", tr: "Varmak" },
  { en: "Ask", tr: "Sormak" },
  { en: "Assume", tr: "Üstlenmek" },
  { en: "Assure", tr: "Garanti etmek" },
  { en: "Attach", tr: "Yapıştırmak, iliştirmek" },
  { en: "Attempt", tr: "Kalkışmak" },
  { en: "Attend", tr: "Katılmak" },
  { en: "Attract", tr: "Cezbetmek, çekmek" },
  { en: "Avoid", tr: "Kaçınmak, önlemek" },
  { en: "Awake", tr: "Uykudan kalkmak" },
  { en: "Bake", tr: "Fırında pişirmek" },
  { en: "Be", tr: "Var olmak, bulunmak" },
  { en: "Beat", tr: "Dayak atmak, vurmak" },
  { en: "Become", tr: "... haline gelmek" },
  { en: "Beg", tr: "Yalvarmak" },
  { en: "Begin", tr: "Başlamak" },
  { en: "Behave", tr: "Davranmak" },
  { en: "Believe", tr: "İnanmak" },
  { en: "Belong", tr: "Ait olmak" },
  { en: "Bet", tr: "İddiaya girmek" },
  { en: "Bind", tr: "Sarmak, kaplamak" },
  { en: "Bite", tr: "Isırmak" },
  { en: "Blow", tr: "Üflemek, esmek" },
  { en: "Boil", tr: "Kaynamak" },
  { en: "Borrow", tr: "Ödünç almak" },
  { en: "Bounce", tr: "Zıplamak, sekmek" },
  { en: "Break", tr: "Kırmak, bozmak" },
  { en: "Breed", tr: "Doğurmak, yavrulamak" },
  { en: "Bring", tr: "Getirmek" },
  { en: "Build", tr: "İnşa etmek" },
  { en: "Burn", tr: "Yanmak" },
  { en: "Buy", tr: "Satın almak" },
  { en: "Calculate", tr: "Hesaplamak" },
  { en: "Can", tr: "Olabilmek, -a bilmek" },
  { en: "Care", tr: "Önem vermek, bakım" },
  { en: "Carry", tr: "Taşımak" },
  { en: "Catch", tr: "Yakalamak" },
  { en: "Celebrate", tr: "Kutlamak" },
  { en: "Change", tr: "Değiştirmek" },
  { en: "Choose", tr: "Seçmek" },
  { en: "Claim", tr: "Talep, iddia etmek" },
  { en: "Climb", tr: "Tırmanmak" },
  { en: "Come", tr: "Gelmek" },
  { en: "Commit", tr: "Suç işlemek" },
  { en: "Communicate", tr: "İletişim kurmak" },
  { en: "Compare", tr: "Karşılaştırmak" },
  { en: "Compete", tr: "Rekabet etmek" },
  { en: "Complain", tr: "Şikayet etmek" },
  { en: "Complete", tr: "Tamamlamak" },
  { en: "Concern", tr: "Endişelenmek" },
  { en: "Confirm", tr: "Onaylamak" },
  { en: "Consent", tr: "Razı olmak" },
  { en: "Consider", tr: "Göz önünde bulundurmak" },
  { en: "Consist", tr: "-den meydana gelmek" },
  { en: "Consult", tr: "Danışmak" },
  { en: "Contain", tr: "Kapsamak, içermek" },
  { en: "Continue", tr: "Devam etmek" },
  { en: "Convince", tr: "İkna etmek" },
  { en: "Cook", tr: "Yemek pişirmek" },
  { en: "Cost", tr: "Mâl olmak" },
  { en: "Count", tr: "Saymak" },
  { en: "Create", tr: "Yaratmak" },
  { en: "Criticize", tr: "Eleştirmek" },
  { en: "Cry", tr: "Ağlamak" },
  { en: "Cut", tr: "Kesmek" },
  { en: "Dance", tr: "Dans etmek" },
  { en: "Deal", tr: "Anlaşma, iş yapmak" },
  { en: "Decide", tr: "Karar vermek" },
  { en: "Delay", tr: "Gecikmek, ertelemek" },
  { en: "Demand", tr: "Talep etmek" },
  { en: "Deny", tr: "Reddetmek" },
  { en: "Depend", tr: "Bağlı olmak" },
  { en: "Describe", tr: "Tanımlamak" },
  { en: "Deserve", tr: "Hak etmek" },
  { en: "Desire", tr: "Arzulamak" },
  { en: "Destroy", tr: "Yok etmek" },
  { en: "Determine", tr: "Kararlaştırmak" },
  { en: "Develop", tr: "Geliştirmek" },
  { en: "Disagree", tr: "Aynı fikirde olmamak" },
  { en: "Discover", tr: "Keşfetmek" },
  { en: "Discuss", tr: "Tartışmak" },
  { en: "Dislike", tr: "Hoşlanmamak" },
  { en: "Distribute", tr: "Dağıtmak, bölmek" },
  { en: "Do", tr: "Yapmak" },
  { en: "Doubt", tr: "Şüphelenmek" },
  { en: "Drag", tr: "Sürüklemek" },
  { en: "Dream", tr: "Rüya görmek" },
  { en: "Drill", tr: "Delmek" },
  { en: "Drink", tr: "İçmek" },
  { en: "Drive", tr: "Araç sürmek" },
  { en: "Drop", tr: "Düşmek, düşürmek" },
  { en: "Dry", tr: "Kurutmak" },
  { en: "Earn", tr: "Para kazanmak" },
  { en: "Eat", tr: "Yemek" },
  { en: "Emphasize", tr: "Vurgulamak" },
  { en: "Enable", tr: "Olanak vermek" },
  { en: "Encourage", tr: "Cesaretlendirmek" },
  { en: "Engage", tr: "Nişanlanmak" },
  { en: "Enhance", tr: "Arttırmak, yükseltmek" },
  { en: "Enjoy", tr: "Tadını çıkarmak" },
  { en: "Ensure", tr: "Garantiye almak" },
  { en: "Entail", tr: "Şarta bağlamak" },
  { en: "Enter", tr: "İçeri girmek" },
  { en: "Establish", tr: "Kurmak" },
  { en: "Examine", tr: "Muayene etmek" },
  { en: "Exist", tr: "Var olmak" },
  { en: "Expand", tr: "Yayılmak" },
  { en: "Expect", tr: "Ummak" },
  { en: "Experiment", tr: "Deney yapmak" },
  { en: "Explain", tr: "Açıklamak" },
  { en: "Explore", tr: "Keşfetmek, araştırmak" },
  { en: "Extend", tr: "Genişletmek, uzatmak" },
  { en: "Fail", tr: "Başarısızlığa uğramak" },
  { en: "Fall", tr: "Düşmek" },
  { en: "Feed", tr: "Beslemek" },
  { en: "Feel", tr: "Hissetmek" },
  { en: "Fight", tr: "Dövüşmek" },
  { en: "Find", tr: "Bulmak" },
  { en: "Finish", tr: "Bitirmek" },
  { en: "Fit", tr: "Uymak" },
  { en: "Fly", tr: "Uçmak" },
  { en: "Fold", tr: "Bükülmek, katlamak" },
  { en: "Follow", tr: "Takip etmek" },
  { en: "Forbid", tr: "Yasaklamak" },
  { en: "Forget", tr: "Unutmak" },
  { en: "Forgive", tr: "Affetmek" },
  { en: "Freeze", tr: "Donmak" },
  { en: "Fry", tr: "Yağda kızartmak" },
  { en: "Generate", tr: "Meydana getirmek" },
  { en: "Get", tr: "Elde etmek" },
  { en: "Give", tr: "Vermek" },
  { en: "Go", tr: "Gitmek" },
  { en: "Grow", tr: "Büyümek" },
  { en: "Hang", tr: "Asmak" },
  { en: "Happen", tr: "Olmak, meydana gelmek" },
  { en: "Hate", tr: "Nefret etmek" },
  { en: "Have", tr: "Sahip olmak" },
  { en: "Hear", tr: "Duymak" },
  { en: "Hesitate", tr: "Tereddüt etmek" },
  { en: "Hide", tr: "Gizlemek" },
  { en: "Hit", tr: "Çarpmak" },
  { en: "Hold", tr: "Tutmak" },
  { en: "Hope", tr: "Umut etmek" },
  { en: "Hug", tr: "Sarılmak" },
  { en: "Hurry", tr: "Acele etmek" },
  { en: "Hurt", tr: "Yaralamak" },
  { en: "Identify", tr: "Kimliğini tespit etmek" },
  { en: "Ignore", tr: "Görmezden gelmek" },
  { en: "Imagine", tr: "Hayal etmek" },
  { en: "Impress", tr: "Etkilemek" },
  { en: "Improve", tr: "Geliştirmek" },
  { en: "Include", tr: "İçermek" },
  { en: "Incorporate", tr: "Firma kurmak" },
  { en: "Indicate", tr: "İşaret etmek" },
  { en: "Inform", tr: "Bilgilendirmek" },
  { en: "Insist", tr: "Israr etmek" },
  { en: "Install", tr: "Kurmak" },
  { en: "Intend", tr: "Niyet etmek" },
  { en: "Introduce", tr: "Tanıştırmak" },
  { en: "Invest", tr: "Yatırım yapmak" },
  { en: "Investigate", tr: "Soruşturmak" },
  { en: "Involve", tr: "Kapsamak" },
  { en: "Iron", tr: "Ütülemek" },
  { en: "Jump", tr: "Zıplamak" },
  { en: "Justify", tr: "Haklı göstermek" },
  { en: "Keep", tr: "Tutmak, saklamak" },
  { en: "Kick", tr: "Tekmelemek" },
  { en: "Kiss", tr: "Öpmek" },
  { en: "Kneel", tr: "Diz çökmek" },
  { en: "Knit", tr: "Örmek" },
  { en: "Know", tr: "Bilmek" },
  { en: "Lack", tr: "Eksik olmak" },
  { en: "Laugh", tr: "Gülmek" },
  { en: "Lay", tr: "Sermek" },
  { en: "Lean", tr: "Eğilmek, yaslanmak" },
  { en: "Leap", tr: "Sıçramak, atlamak" },
  { en: "Learn", tr: "Öğrenmek" },
  { en: "Leave", tr: "Ayrılmak, terk etmek" },
  { en: "Lend", tr: "Ödünç vermek" },
  { en: "Lie", tr: "Yalan söylemek" },
  { en: "Lift", tr: "Kaldırmak" },
  { en: "Light", tr: "Işık saçmak, parlatmak" },
  { en: "Like", tr: "Beğenmek" },
  { en: "Listen", tr: "Dinlemek" },
  { en: "Look", tr: "Bakmak" },
  { en: "Lose", tr: "Kaybetmek" },
  { en: "Love", tr: "Sevmek" },
  { en: "Maintain", tr: "Bakım yapmak, devam ettirmek" },
  { en: "Make", tr: "Yapmak" },
  { en: "Manage", tr: "Yönetmek" },
  { en: "Matter", tr: "Önemli olmak" },
  { en: "Mean", tr: "Demek istemek, kastetmek" },
  { en: "Measure", tr: "Ölçmek" },
  { en: "Meet", tr: "Tanışmak" },
  { en: "Melt", tr: "Erimek" },
  { en: "Mention", tr: "Belirtmek" },
  { en: "Mind", tr: "Önemsemek" },
  { en: "Miss", tr: "Özlemek" },
  { en: "Mix", tr: "Karıştırmak" },
  { en: "Must", tr: "Gerekmek, -meli -malı" },
  { en: "Need", tr: "İhtiyaç duymak" },
  { en: "Neglect", tr: "İhmal etmek" },
  { en: "Negotiate", tr: "Pazarlık etmek" },
  { en: "Observe", tr: "Gözlemlemek" },
  { en: "Obtain", tr: "Elde etmek" },
  { en: "Occur", tr: "Meydana gelmek" },
  { en: "Offer", tr: "Teklif vermek" },
  { en: "Open", tr: "Açmak" },
  { en: "Operate", tr: "Ameliyat etmek" },
  { en: "Order", tr: "Sipariş vermek" },
  { en: "Organize", tr: "Organize etmek" },
  { en: "Ought to", tr: "-meli/-malı (yapmalı/bilmeli vb)" },
  { en: "Overcome", tr: "Üstesinden gelmek" },
  { en: "Overtake", tr: "Yetişip geçmek" },
  { en: "Own", tr: "Sahip olmak" },
  { en: "Paint", tr: "Boyamak" },
  { en: "Participate", tr: "Katılmak" },
  { en: "Pay", tr: "Ödemek" },
  { en: "Peel", tr: "Soymak" },
  { en: "Perform", tr: "Rol yapmak" },
  { en: "Persuade", tr: "İkna etmek" },
  { en: "Pick up", tr: "Toplamak, almak" },
  { en: "Pinch", tr: "Çimdiklemek, sıkmak" },
  { en: "Plan", tr: "Planlamak" },
  { en: "Play", tr: "Oynamak" },
  { en: "Point", tr: "İşaret etmek" },
  { en: "Postpone", tr: "Ertelemek" },
  { en: "Practice", tr: "Alıştırma yapmak" },
  { en: "Prefer", tr: "Tercih etmek" },
  { en: "Prepare", tr: "Hazırlamak" },
  { en: "Pretend", tr: "Yapar gibi görünmek" },
  { en: "Prevent", tr: "Önlemek" },
  { en: "Proceed", tr: "İlerlemek" },
  { en: "Promise", tr: "Söz vermek" },
  { en: "Propose", tr: "Önermek" },
  { en: "Protect", tr: "Korumak" },
  { en: "Prove", tr: "Kanıtlamak" },
  { en: "Pull", tr: "Çekmek" },
  { en: "Punch", tr: "Yumruklamak" },
  { en: "Pursue", tr: "İzlemek, takip etmek" },
  { en: "Push", tr: "İtmek" },
  { en: "Put", tr: "Koymak" },
  { en: "Qualify", tr: "Nitelendirmek" },
  { en: "Quit", tr: "Bırakmak, çıkmak" },
  { en: "React", tr: "Tepki göstermek" },
  { en: "Read", tr: "Okumak" },
  { en: "Realize", tr: "Farkına varmak" },
  { en: "Recall", tr: "Hatırlamak" },
  { en: "Receive", tr: "Teslim almak" },
  { en: "Recollect", tr: "Anımsamak" },
  { en: "Recommend", tr: "Tavsiye etmek" },
  { en: "Reduce", tr: "Azaltmak" },
  { en: "Refer", tr: "Anmak, bahsetmek" },
  { en: "Reflect", tr: "Yansıtmak" },
  { en: "Refuse", tr: "Reddetmek" },
  { en: "Regret", tr: "Pişman olmak" },
  { en: "Relate", tr: "Bağlantı kurmak" },
  { en: "Relax", tr: "Rahatlamak" },
  { en: "Relieve", tr: "Yüreğine su serpmek" },
  { en: "Rely", tr: "Güvenmek" },
  { en: "Remain", tr: "Geriye kalmak" },
  { en: "Remember", tr: "Hatırlamak" },
  { en: "Remind", tr: "Hatırlatmak" },
  { en: "Repair", tr: "Tamir etmek" },
  { en: "Replace", tr: "Yerine geçmek" },
  { en: "Represent", tr: "Temsil etmek" },
  { en: "Require", tr: "Gerek, ihtiyaç duymak" },
  { en: "Resent", tr: "Alınmak, içerlemek" },
  { en: "Resist", tr: "Dayanmak, direnmek" },
  { en: "Retire", tr: "Emekli olmak" },
  { en: "Ride", tr: "Binmek" },
  { en: "Ring", tr: "Çalmak (telefon/zil)" },
  { en: "Rise", tr: "Doğmak, yükselmek" },
  { en: "Risk", tr: "Göze almak" },
  { en: "Run", tr: "Koşmak" },
  { en: "Satisfy", tr: "Tatmin etmek" },
  { en: "Say", tr: "Söylemek" },
  { en: "Scrub", tr: "Ovmak" },
  { en: "See", tr: "Görmek" },
  { en: "Seem", tr: "Gözükmek" },
  { en: "Sell", tr: "Satmak" },
  { en: "Send", tr: "Göndermek" },
  { en: "Serve", tr: "Hizmet etmek" },
  { en: "Set", tr: "Kurmak" },
  { en: "Settle", tr: "Yerleşmek, oturtmak" },
  { en: "Sew", tr: "Dikiş dikmek" },
  { en: "Shake", tr: "Sallamak" },
  { en: "Shine", tr: "Parıldamak, parlamak" },
  { en: "Shoot", tr: "Film çekmek, ateş etmek" },
  { en: "Show", tr: "Göstermek" },
  { en: "Shut", tr: "Kapatmak" },
  { en: "Sink", tr: "Suya batmak, batırmak" },
  { en: "Sit", tr: "Oturmak" },
  { en: "Sing", tr: "Şarkı söylemek" },
  { en: "Ski", tr: "Kayak yapmak" },
  { en: "Sleep", tr: "Uyumak" },
  { en: "Slice", tr: "Dilimlemek" },
  { en: "Smell", tr: "Koklamak" },
  { en: "Snore", tr: "Horlamak, Hırıldamak" },
  { en: "Solve", tr: "Çözmek, halletmek" },
  { en: "Speak", tr: "Konuşmak" },
  { en: "Specify", tr: "Belirlemek" },
  { en: "Spell", tr: "Hecelemek" },
  { en: "Spend", tr: "Harcamak" },
  { en: "Spill", tr: "Dökmek, dökülmek" },
  { en: "Spit", tr: "Tükürmek" },
  { en: "Spread", tr: "Yaymak, yayılmak" },
  { en: "Squat", tr: "Çömelmek" },
  { en: "Stand", tr: "Katlanmak, ayakta durmak" },
  { en: "Start", tr: "Başlamak, başlatmak" },
  { en: "Steal", tr: "Hırsızlık yapmak" },
  { en: "Stick", tr: "Saplamak, batırmak" },
  { en: "Sting", tr: "Batmak, sokmak" },
  { en: "Stir", tr: "Karıştırmak" },
  { en: "Stop", tr: "Durmak" },
  { en: "Strike", tr: "Çarpmak, vurmak" },
  { en: "Study", tr: "Ders çalışmak" },
  { en: "Submit", tr: "Sunmak, ibraz etmek" },
  { en: "Succeed", tr: "Başarmak" },
  { en: "Suffer", tr: "Acı çekmek" },
  { en: "Suggest", tr: "Önermek" },
  { en: "Supply", tr: "Sağlamak" },
  { en: "Suppose", tr: "Sanmak" },
  { en: "Surprise", tr: "Sürpriz yapmak" },
  { en: "Survive", tr: "Sağ kalmak" },
  { en: "Swear", tr: "Yemin etmek" },
  { en: "Swell", tr: "Şişmek, kabarmak" },
  { en: "Swim", tr: "Yüzmek" },
  { en: "Swing", tr: "Sallanmak" },
  { en: "Take", tr: "Almak" },
  { en: "Taste", tr: "Tatmak" },
  { en: "Teach", tr: "Öğretmek" },
  { en: "Tear", tr: "Yırtmak, gözyaşı" },
  { en: "Tell", tr: "Anlatmak" },
  { en: "Tend", tr: "Eğilimi olmak" },
  { en: "Think", tr: "Düşünmek" },
  { en: "Throw", tr: "Fırlatmak" },
  { en: "Tolerate", tr: "Tahammül etmek" },
  { en: "Translate", tr: "Tercüme etmek" },
  { en: "Try", tr: "Denemek" },
  { en: "Understand", tr: "Anlamak" },
  { en: "Vacuum", tr: "Vakumlamak" },
  { en: "Value", tr: "Değer vermek" },
  { en: "Vary", tr: "Çeşitlendirmek" },
  { en: "Volunteer", tr: "Gönüllü olmak" },
  { en: "Wait", tr: "Beklemek" },
  { en: "Wake", tr: "Canlanmak, uyanmak" },
  { en: "Walk", tr: "Yürümek" },
  { en: "Want", tr: "İstemek" },
  { en: "Warn", tr: "Uyarmak" },
  { en: "Wash", tr: "Yıkamak" },
  { en: "Watch", tr: "İzlemek" },
  { en: "Wave", tr: "Dalgalanmak" },
  { en: "Wear", tr: "Giyinmek" },
  { en: "Weight", tr: "Ağırlık yapmak" },
  { en: "Win", tr: "Kazanmak" },
  { en: "Wish", tr: "Dilemek" },
  { en: "Would", tr: "İstemek" },
  { en: "Write", tr: "Yazmak" },
];
